name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22 LTS
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean package -B -DskipTests

      - name: Run Cucumber tests
        run: |
          mvn test -Dmaven.test.failure.ignore=true

      - name: List compiled classes
        run: |
          echo "Listing compiled classes:"
          ls -R target/classes

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/surefire-reports

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/site/jacoco

  code-scanning:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Security audit
        run: npm audit --audit-level=critical

      - name: Snyk security scan
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Create CodeQL config file
        run: |
          mkdir -p .github/codeql
          echo "language: javascript" >> $GITHUB_WORKSPACE/.github/codeql/codeql-config.yml   

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: 'security'
          output: 'codeql-results.sarif'

      - name: Upload CodeQL Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql-results.sarif

      - name: Run SpotBugs
        run: |
          mvn spotbugs:check
          mvn spotbugs:spotbugs
          
      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/spotbugs/spotbugs.xml

      - name: Run Checkstyle
        run: |
          mvn checkstyle:check
          
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

      - name: Run PMD
        run: |
          mvn pmd:pmd

      - name: Upload PMD Report
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: target/pmd.xml

      - name: Codecov analysis
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy-reports:
    runs-on: ubuntu-latest
    needs: code-scanning
    steps:
      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Download SpotBugs Report
        uses: actions/download-artifact@v3
        with:
          name: spotbugs-report
          path: reports/spotbugs

      - name: Download Checkstyle Report
        uses: actions/download-artifact@v3
        with:
          name: checkstyle-report
          path: reports/checkstyle

      - name: Download PMD Report
        uses: actions/download-artifact@v3
        with:
          name: pmd-report
          path: reports/pmd

     