on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22 LTS
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
          id: cache
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

        - name: Build with Maven
          run: |
            mvn clean package -B -DskipTests

        - name: Run Cucumber tests
          run: |
            mvn test -B -Dcucumber.filter.tags="@springbot"


  codeql-analysis:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'

      - name: Build the code
        run: mvn clean package -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22 LTS
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.sh https://raw.githubusercontent.com/jeremylong/DependencyCheck/6.5.0/bin/dependency-check.sh
          chmod +x dependency-check.sh
          ./dependency-check.sh --version

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check.sh --project "BooK-RAss-CCr" --scan . --format "ALL" --out . --failOnCVSS 7